### ISSUE TITLE
Virtual Columns Support

### ISSUE THREAD

**Issue by JLynch7** [JLynch7/SlickGrid#22]
Add support for virtual columns similar to virtual rows

**Comment by JLynch7** [comment]
Added by mleibman and merged with frozen rows/columns branch in 21019136b8d104f34a00bfbd00b715fc581f980c

**Comment by laurencei** [comment]
FYI - this commit BREAKS your fixed column code.

If you have a large number of columns, say 30, then when you scroll to the right, eventually the new "virtualisation" of the columns kicks in, and the fixed columns turn blank.

You can replicate this issue on your "example-frozen-columns.html" file. Just add another 20 columns of random data, scroll to the right, eventually your fixed columns turn blank.

**Comment by JLynch7** [comment]
Fixed in d15f585a4457dff880e8353d16db33db586cb8e6.  Please verify and let me know.

**Comment by laurencei** [comment]
Yep - that seems to have fixed it.

The only other thing is the original commit seems to have changed something about jQuery 'tabs' and slickgrids. It works ok on the mleibman version, but in your version some of my table tabs stopped working. I'm not sure what the issue is yet, because it works on some tables and not others - and it only started being an issue with commit 2101913. If I roll back - the issue disappears.

I'll post more if I can narrow it down for you. Thanks again.

**Comment by JLynch7** [comment]
Which version of jQuery and jQuery UI are you using?

**Comment by laurencei** [comment]
jquery-1.7.1 and jquery-ui-1.8.16

**Comment by JLynch7** [comment]
I'm not able to reproduce the tabs issue using the latest commit.  Can you verify this is still an issue?

**Comment by JLynch7** [comment]
The tabs issue was resolved and confirmed in issue #28
