### ISSUE TITLE
Header Row does not work with columns more than width of div

### ISSUE THREAD

**Issue by sipte** [JLynch7/SlickGrid#38]
In example-header-row.html if you change number of columns to 20, header row doesn't get populated. (line 64)

Also line 57 in example-header-row.html is missing an comma

This is on branch SlickGrid-2.0-frozenRowsAndColumns

**Comment by sipte** [comment]
Also If I add frozenColumn option, then header row shows up, but it doesnt scroll on scroll event

**Comment by gcko** [comment]
Looks like $headerRowL/headerRowR's width is being set to canvasWidthL/canvasWidthR respectively in `function updateCanvasWidth`. Changing it so that it uses `headersWidthL` & `headersWidthR` allows them to scroll when interacting with the body. Note that it will not scroll when focused/hovered over the Header Row (as designed by @mliebman)

EDIT:
This is actually incorrect, it is more proper to set the following `$headerRowScrollerR.width(viewportW - canvasWidthL);` 

Also there is an @TODO in the code re: the spacers at the end of the headerRow columns. I implemented a spacer for HeaderRowScrollerR. Again i'll look to submit a patch shortly

**Comment by gcko** [comment]
I'll submit a patch shortly

**Comment by sipte** [comment]
Thanks :)
