### ISSUE TITLE
SlickGrid Dissapearing Text in Frozen Column on Horizontal Scroll

### ISSUE THREAD

**Issue by stplajay** [JLynch7/SlickGrid#84]
I have used SlickGrid in my project. Grid contains 30 columns. Initially grid works fine. it has horizontal as well as vertical scroll. I have frozen first column.
Issue is that when i scroll it horizontally and reached at right most and then after vertical scrolling frozen column data doesn't display. any suggestion please help.

![initial page jpg](https://cloud.githubusercontent.com/assets/13213492/8795230/d4b6be74-2fa8-11e5-896e-c0dc0fed997b.png)

![after scrolling jpg](https://cloud.githubusercontent.com/assets/13213492/8795233/dac7d12c-2fa8-11e5-828a-ed12db8674b9.png)

**Comment by Mingun** [comment]
You are using branch **2.0-frozenRowsAndColumns**, right? This is because bug in SlickGrid: in [line 1947 slick.grid.js file](https://github.com/JLynch7/SlickGrid/blob/2.0-frozenRowsAndColumns/slick.grid.js#L1947) missing five parameter. Because of that SlickGrid not rerendered frozen cells.

### Quick Fix

Add `d` as five parameter to `appendCellHtml` in line 1947.

``` js
        } else if (options.frozenColumn > -1 && i <= options.frozenColumn) {
          appendCellHtml(stringArrayL, row, i, colspan, d);
        }
```

### Why this error appears?

Consider the [`render`](https://github.com/JLynch7/SlickGrid/blob/2.0-frozenRowsAndColumns/slick.grid.js#L2643-L2675) function. First it takes [rendered rows](https://github.com/JLynch7/SlickGrid/blob/2.0-frozenRowsAndColumns/slick.grid.js#L2648), and then [deletes](https://github.com/JLynch7/SlickGrid/blob/2.0-frozenRowsAndColumns/slick.grid.js#L2651) all rows from the cache, except the specified range. Because rendered rows takes with reserve in [three rows](https://github.com/JLynch7/SlickGrid/blob/2.0-frozenRowsAndColumns/slick.grid.js#L2365), an error occurs only after vertical scroll for more than three rows, when starts rendering missing rows in [`renderRows`](https://github.com/JLynch7/SlickGrid/blob/2.0-frozenRowsAndColumns/slick.grid.js#L2659) function. This function [call `appendRowHtml`](https://github.com/JLynch7/SlickGrid/blob/2.0-frozenRowsAndColumns/slick.grid.js#L2580) for each rendered row, and that function [check position right border](https://github.com/JLynch7/SlickGrid/blob/2.0-frozenRowsAndColumns/slick.grid.js#L1935-L1948) every cell in row. If that position in visible range, cell rendered properly. But for frozen columns, values in `columnPosRight` array after horizontal scroll become smaller left border of viewport. And the execution goes to second branch of `if` condition. In that branch missing five parameter `d` in call `appendCellHtml`. Because of that cell [do not rendered](https://github.com/JLynch7/SlickGrid/blob/2.0-frozenRowsAndColumns/slick.grid.js#L1980-L1984).

**Comment by stplajay** [comment]
Hi,
Thank you so much. I have incorporated your comment into my solution and issue has been fixed.
Thanks once again for your quick response. :)
